# Generated by Django 3.2.12 on 2022-04-27 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.CharField(default='', max_length=2000)),
                ('raw_score', models.FloatField(default=0)),
                ('sentiment', models.CharField(default='Neutral', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpellCheckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_word', models.CharField(default='', max_length=50)),
                ('dictionary', models.CharField(default='', max_length=5000)),
                ('word_count', models.IntegerField(default=3)),
                ('correct_words', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('is_root', models.BooleanField(default=False)),
                ('parent_folder_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.folder')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('folder_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.folder')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
