# Generated by Django 4.0.4 on 2022-05-05 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SentimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.CharField(default='', max_length=2000)),
                ('raw_score', models.FloatField(default=0)),
                ('sentiment', models.CharField(default='Neutral', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpellCheckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_word', models.CharField(default='', max_length=50)),
                ('dictionary', models.CharField(default='', max_length=5000)),
                ('word_count', models.IntegerField(default=3)),
                ('correct_words', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_root', models.BooleanField(default=False)),
                ('parent_folder_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.foldermodel')),
            ],
        ),
    ]
