# Generated by Django 4.0.3 on 2022-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.CharField(default='', max_length=500)),
                ('raw_score', models.FloatField(default=0)),
                ('sentiment', models.CharField(default='neutral', max_length=100)),
            ],
        ),
    ]
