# Generated by Django 3.2.12 on 2022-04-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellCheckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_word', models.CharField(default='', max_length=50)),
                ('dictionary', models.CharField(default='', max_length=5000)),
                ('word_count', models.IntegerField(default=3)),
                ('correct_words', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='query_string',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
