# Generated by Django 4.0.3 on 2022-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
