# Generated by Django 4.0.4 on 2022-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20220428_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmodel',
            old_name='doc_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='documentmodel',
            old_name='folder_id',
            new_name='parent_folder_id',
        ),
        migrations.RenameField(
            model_name='foldermodel',
            old_name='folder_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='foldermodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
