# Generated by Django 3.2.12 on 2022-04-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_sentimentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentmodel',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=100),
        ),
    ]
