# Generated by Django 4.0.4 on 2022-05-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentmodel',
            name='raw_score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
