# Generated by Django 4.0.3 on 2022-05-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
