# Generated by Django 3.2.12 on 2022-04-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_sentimentmodel_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder_id',
            field=models.IntegerField(default=0),
        ),
    ]
